### ISSUE TITLE
Exception on cancelling large file > 400MB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#11]
```
Exception in thread "Thread-17" 
gwtupload.server.exceptions.UploadCanceledException
    at gwtupload.server.UploadServlet.cancelUpload(UploadServlet.java:312)
    at gwtupload.server.UploadServlet.doGet(UploadServlet.java:155)
    at gwtupload.server.UploadAction.doGet(UploadAction.java:118)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at 
org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInter
nal(ServletWr
appingController.java:158)
    at 
org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractCon
troller.java:
153)
    at 
org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(Simple
ControllerH
andlerAdapter.java:48)
    at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:875)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
    at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:571)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1097)
    at com.tyrrells.sinmo.server.filters.CacheFilter.doFilter(CacheFilter.java:30)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:378)
    at 
org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(Filt
erSecurityIntercep
tor.java:109)
    at 
org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(Fi
lterSecurityInterce
ptor.java:83)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at 
org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(Exceptio
nTranslationFilte
r.java:101)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at 
org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFil
terHttp(Ano
nymousProcessingFilter.java:105)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at 
org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractPr
ocessingFilter.jav
a:277)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at com.tyrrells.sinmo.server.filters.GWTLogoutFilter.doFilterHttp(GWTLogoutFilter.java:89)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at 
org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilte
rHttp(HttpSessi
onContextIntegrationFilter.java:235)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at 
org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(F
ilterChainProxy.ja
va:390)
    at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:175)
    at 
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFi
lterProxy.java:
236)
    at 
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterPr
oxy.java:167)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:729)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.handler.RequestLogHandler.handle(RequestLogHandler.java:49)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at 
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.ja
va:829)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:513)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)
```

Original issue reported on code.google.com by `james.t....@gmail.com` on 17 Sep 2009 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Although it is a normal error in the logs, I have changed the method in order to
avoid these messages in the logs, please download and check it.

Thank you for reporting.

```

Original comment by `manuel.carrasco.m` on 17 Sep 2009 at 4:53
- Changed state: **Fixed**
