### ISSUE TITLE
java.lang.NoSuchFieldError: logger at gwtupload.server.gae.MemCacheUploadListener.current

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#114]
```
What steps will reproduce the problem?
1. Use SmartGwt and GWTUpload with GAE
2. Try to upload a csv file to a servlet which extends AppEngineUploadAction

What is the expected output? What do you see instead?
Servlet response should come.

What version of the product are you using? On what operating system?
gwtupload-gae-0.6.4-SNAPSHOT
gwtupload-0.6.4-20110712.073705-11
commons-fileupload-1.2.2
commons-io-2.0.1
log4j-1.2.16

Please provide any additional information below.
Response Body:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 logger</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /BulkFileUpload1. Reason:
<pre>    logger</pre></p><h3>Caused by:</h3><pre>java.lang.NoSuchFieldError: 
logger
    at gwtupload.server.gae.MemCacheUploadListener.current(MemCacheUploadListener.java:63)
    at gwtupload.server.gae.AppEngineUploadAction.getCurrentListener(AppEngineUploadAction.java:69)
    at gwtupload.server.UploadServlet.parsePostRequest(UploadServlet.java:768)
    at gwtupload.server.UploadAction.doPost(UploadAction.java:159)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:58)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.BackendServersFilter.doFilter(BackendServersFilter.java:94)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.utils.jetty.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:70)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:351)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>                            

<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

```

Original issue reported on code.google.com by `hemanthv...@gmail.com` on 19 Jul 2011 at 10:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 24 Jul 2011 at 8:14
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 24 Jul 2011 at 8:15

**Comment by GoogleCodeExporter** [comment]
```
Last changes in gwtupload-gae does not manifest this issue, could you test?

thanks
- Manolo
```

Original comment by `manuel.carrasco.m` on 1 Jun 2012 at 10:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 3 Dec 2012 at 9:02
- Changed state: **Done**
