### ISSUE TITLE
NoSuchMethodError in FilesApiUploadAction.init(FilesApiUploadAction.java:91)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#124]
```
What steps will reproduce the problem?
1.Adding "gwtupload-gae"dependency in my pom.xml
2.Using this as servlet: gwtupload.server.gae.FilesApiUploadAction
3.activate <load-on-startup> for the servlet)
3.typing mvn clean gae:run

What is the expected output? What do you see instead?
server running 

What version of the product are you using? On what operating system?
0.6.4-SNAPSHOT

Please provide any additional information below.
I get this error while the server is starting:
java.lang.NoSuchMethodError: 
gwtupload.server.UploadLogger.info(Ljava/lang/String;)V
    at gwtupload.server.gae.FilesApiUploadAction.init(FilesApiUploadAction.java:91)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
    at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:186)
    at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:149)
    at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:170)
    at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:164)
    at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
    at com.google.appengine.tools.development.DevAppServerMain.<init>(DevAppServerMain.java:113)
    at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:89)

```

Original issue reported on code.google.com by `DoctorMi...@gmail.com` on 30 Sep 2011 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
I think there is an error when you deployed the package to the maven repo: I 
tried to go directly from your source code and then I rebuilt from there after 
having touched the "FilesApiUploadAction" file and not it works!

Please let us know where is the new location of your source code: I would like 
to help you in the development because I am using this on my projects and I 
really need some improvements, that I can code on my own!
```

Original comment by `DoctorMi...@gmail.com` on 30 Sep 2011 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
I have deployed again the snapshots, could you try again.

To get and compile the sources you have to install svn and maven and run:

svn checkout http://gwtupload.googlecode.com/svn/trunk/GwtUpload gwtupload
cd gwtupload/core 
mvn package

then you should have the new .jar file in the target folder.



```

Original comment by `manuel.carrasco.m` on 9 Nov 2011 at 11:06
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 22 Nov 2011 at 3:26
- Changed state: **Fixed**
