### ISSUE TITLE
file is not uploaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#138]
```
What steps will reproduce the problem?

1. create any application using gwtupload 
2.Followed all the steps given in this link
   http://code.google.com/p/gwtupload/wiki/GwtUpload_GettingStarted

3.when i select an image the progrees bar of uploading goies till 16%
After that i get an error.



What is the expected output? What do you see instead?
Out put should be the xyz.jpg or xyz.doc file. I see an error

java.lang.NoClassDefFoundError: java.rmi.server.UID is a restricted class. 
Please see the Google  App Engine developer's guide for more details.
    at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:51)
    at org.apache.commons.fileupload.disk.DiskFileItem.<clinit>(DiskFileItem.java:103)
    at org.apache.commons.fileupload.disk.DiskFileItemFactory.createItem(DiskFileItemFactory.java:196)
    at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:358)
    at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
    at gwtupload.server.UploadServlet.parsePostRequest(UploadServlet.java:774)


What version of the product are you using? On what operating system?


Please provide any additional information below.
GWT 2.4.0,
commons-io-1.4.jar
commons-fileupload-1.2.1.jar
gwt-upload-0.6.4.jar

```

Original issue reported on code.google.com by `pratyush...@gmail.com` on 8 Mar 2012 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
Your project is set to use Google Application Engine (GAE), so you have to do 
either: set your project to no use GAE, or include the library gwtupload-gae 
and configure your servlet to use any of the servlet provided with 
gwtupload-gae.

If you are planning to use GAE use version 0.6.5-SNAPSHOT of gwtupload 
libraries which fixes many problems.
```

Original comment by `manuel.carrasco.m` on 23 May 2012 at 3:37
- Changed state: **Done**
