### ISSUE TITLE
NullPointerException in UploadServlet.getMessage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#148]
```
What steps will reproduce the problem?
1. Deploy app with gwtupload on GAE
2. Try to upload picture

What is the expected output? What do you see instead?
This seems to be bug in error handling, so although desired output would be 
uploaded picture, the expected output is error message on client side. 
The client does nothing and this appears in the server log:
/upload
java.lang.NullPointerException
    at gwtupload.server.UploadServlet.getMessage(UploadServlet.java:228)
    at gwtupload.server.gae.BlobstoreUploadAction.doPost(BlobstoreUploadAction.java:196)

What version of the product are you using? On what operating system?
gwtupload + gwtupload-gae 0.6.4
GAE SDK 1.6.5
GWT SDK 2.4.0
Firefox 12, Ubuntu 11.10

Please provide any additional information below.
I successfully use AppEngineUploadAction and I'm trying to switch to 
BlobstoreUploadAction. There seems to be some undelying problem, but I haven't 
figured it out yet.

```

Original issue reported on code.google.com by `jakub.st...@czechgeeks.cz` on 16 May 2012 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
which locale are you using?

It seems a problem when getting the localized message

Does it only happen in GAE?
Does http://gwtupload.alcala.org works for you ?
```

Original comment by `manuel.carrasco.m` on 23 May 2012 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
I'm using English locale. It only happened in GAE. The demo app works ok.

I've somehow fixed the underlying problem (I'm not sure how though), so I'm not 
experiencing this issue anymore.

```

Original comment by `JakubSte...@gmail.com` on 29 May 2012 at 9:20

**Comment by GoogleCodeExporter** [comment]
```
Ok, I close this issue right now, if you experiment the issue again check with 
last snapshot (I changed some things lately) and reopen it. 

Thanks


```

Original comment by `manuel.carrasco.m` on 30 May 2012 at 11:26
- Changed state: **Done**
