### ISSUE TITLE
Problem encoding 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#149]
```
I used gwtupload into web project, my i18n is spanish, but I have a problem 
with response when the file exceeds the maximum allowed.

I have used the application in several web servers as Jetty and Glassfish and 
both the same problem occurs.

The web.xml file is set the enconding param utf-8, also I added the java param.

Please, help me with this problem.
```

Original issue reported on code.google.com by `lfcorte...@gmail.com` on 22 May 2012 at 8:47

Attachments:
- [errorencoding.png](https://storage.googleapis.com/google-code-attachments/gwtupload/issue-149/comment-0/errorencoding.png)

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r988.
```

Original comment by `manuel.carrasco.m` on 24 May 2012 at 8:44
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r988

Thanks for reporting
- Manolo
```

Original comment by `manuel.carrasco.m` on 24 May 2012 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
Other question, How do you recommend to include this change in my project?
```

Original comment by `lfcorte...@gmail.com` on 24 May 2012 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
The snapshot has the change?
```

Original comment by `lfcorte...@gmail.com` on 24 May 2012 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
I change the library to the last snapshot version, but now it's a problem on 
upload: 

java.lang.ClassCastException: java.util.ArrayList cannot be cast to 
java.util.Vector
       at gwtupload.server.UploadServlet.getLastReceivedFileItems(UploadServlet.java:237)
       at gwtupload.server.UploadAction.doPost(UploadAction.java:180)
```

Original comment by `lfcorte...@gmail.com` on 24 May 2012 at 6:44
