### ISSUE TITLE
Problem last snapshot version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#150]
```
I change the library to the last snapshot version, but now it's a problem on 
upload: 

java.lang.ClassCastException: java.util.ArrayList cannot be cast to 
java.util.Vector
       at gwtupload.server.UploadServlet.getLastReceivedFileItems(UploadServlet.java:237)
       at gwtupload.server.UploadAction.doPost(UploadAction.java:180)
```

Original issue reported on code.google.com by `lfcorte...@gmail.com` on 24 May 2012 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
It seems there was a bad snapshot in the repo for a while, could you test the 
last one?.

Are you using maven repos?
```

Original comment by `manuel.carrasco.m` on 31 May 2012 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
Yes, I'm using  maven.
El 31/05/2012 00:56, <gwtupload@googlecode.com> escribi�:
```

Original comment by `lfcorte...@gmail.com` on 31 May 2012 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
Finally, the problem was fixed. Thanks.
```

Original comment by `lfcorte...@gmail.com` on 31 May 2012 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
thanks for reporting
- Manolo
```

Original comment by `manuel.carrasco.m` on 1 Jun 2012 at 9:49
- Changed state: **Fixed**
