### ISSUE TITLE
GWTUpload not compatible with GWT-Designer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#162]
```
What steps will reproduce the problem?
1. Initialize the Uploader
2. Add it to the root panel
3. Switch to designer view (using WindowBuilder plugin of Eclipse)

What is the expected output? What do you see instead?
- The switch should be normal and the widget should be visible with its 
properties listed in the property pane.

What version of the product are you using? On what operating system?
I am using gwtupload-0.6.4.jar / Eclipse Helios / Windows 7 Ultimate / JDK 1.7

Please provide any additional information below.
The stack trace contains the following message:

Internal Error
encountered unexpected internal error. 

This could be caused by a bug or by a misconfiguration issue, conflict, partial 
update, etc.

java.lang.Error: new Uploader()

Stack trace:

java.lang.StackOverflowError
    at java.lang.Exception.<init>(Exception.java:77)
    at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:54)
    at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.wb.internal.core.utils.reflect.ClassLoaderLocalMap.getLocalMap(ClassLoaderLocalMap.java:122)
    at org.eclipse.wb.internal.core.utils.reflect.ClassLoaderLocalMap.get(ClassLoaderLocalMap.java:92)
    at org.eclipse.wb.internal.core.utils.reflect.ClassMap.getMap(ClassMap.java:68)
    at org.eclipse.wb.internal.core.utils.reflect.ClassMap.getMap(ClassMap.java:63)
    at org.eclipse.wb.internal.core.utils.reflect.ClassMap.get(ClassMap.java:45)
    at org.eclipse.wb.internal.core.utils.reflect.ReflectionUtils.getMethodBySignature(ReflectionUtils.java:759)
    at org.eclipse.wb.internal.core.utils.reflect.ReflectionUtils.invokeMethod(ReflectionUtils.java:865)
    at com.google.gdt.eclipse.designer.model.widgets.GwtHierarchyProvider.getChildrenObjects(GwtHierarchyProvider.java:99)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:979)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)
    at org.eclipse.wb.internal.core.model.JavaInfoUtils.fillChildren(JavaInfoUtils.java:983)


```

Original issue reported on code.google.com by `shishirm...@gmail.com` on 16 Sep 2012 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
We will not fix this issue, since we have not enough time to fix issues related 
with the integration of gwtupload with other products. 
Gwtupload should work fine in gwt java classes and uibinder though.

- Manolo
```

Original comment by `manuel.carrasco.m` on 5 Apr 2013 at 10:10
- Changed state: **WontFix**
