### ISSUE TITLE
Gwtupload issues with ie10 and gwt-2.6.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bdshadow/gwtupload#192]
```
Upload works with IE 9 and IE 11, but IE 10 runs into an intinite loop:
...
    at gwtupload.client.DecoratedFileUpload.setSize(DecoratedFileUpload.java:519)
    at gwtupload.client.DecoratedFileUpload$DecoratedFileUploadImplNoClick.resize(DecoratedFileUpload.java:339)
    at gwtupload.client.DecoratedFileUpload.updateSize(DecoratedFileUpload.java:537)
    at gwtupload.client.DecoratedFileUpload.setButtonSize(DecoratedFileUpload.java:493)
    at gwtupload.client.DecoratedFileUpload.setSize(DecoratedFileUpload.java:519)
    at gwtupload.client.DecoratedFileUpload$DecoratedFileUploadImplNoClick.resize(DecoratedFileUpload.java:339)
    at gwtupload.client.DecoratedFileUpload.updateSize(DecoratedFileUpload.java:537)
    at gwtupload.client.DecoratedFileUpload.setButtonSize(DecoratedFileUpload.java:493)
    at gwtupload.client.DecoratedFileUpload.setSize(DecoratedFileUpload.java:519)
    at gwtupload.client.DecoratedFileUpload$DecoratedFileUploadImplNoClick.resize(DecoratedFileUpload.java:339)
    at gwtupload.client.DecoratedFileUpload.updateSize(DecoratedFileUpload.java:537)
    at gwtupload.client.DecoratedFileUpload.setButtonSize(DecoratedFileUpload.java:493)
    at gwtupload.client.DecoratedFileUpload.setSize(DecoratedFileUpload.java:519)
...

The problem semms to be in GWTUpload.gwt.xml.
IE 10 is a new user agent in GWT 2.6, but this is not handeld in the 
configuaration.

With IE 9 and IE 11 DecoratedFileUploadImpl is replaced with 
DecoratedFileUploadImplClick.
With IE 10 DecoratedFileUploadImpl is replaced with 
DecoratedFileUploadImplNoClick.

DecoratedFileUploadImplNoClick implements the resize function which causes the 
infinite loop.
DecoratedFileUploadImplClick does not implement the function.

```

Original issue reported on code.google.com by `manuel.carrasco.m` on 6 Mar 2014 at 5:08
- Merged into: #191

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 2 Apr 2014 at 8:17
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
Original comment by `manuel.carrasco.m` on 28 Apr 2014 at 6:28
- Added labels: **Milestone-1.0.1**
